name: Build and Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build libft Linux
        run: make -C libft fclean all

      - name: Build push_swap Linux
        run: make fclean all

      - name: Create Linux Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}-linux
          name: Release v1.0.${{ github.run_number }}-linux
          files: |
            libft/libft.a
            includes/libft.h
            push_swap

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build libft macOS universal
        run: make -C libft fclean universal

      - name: Build push_swap macOS
        run: make fclean all

      - name: Create macOS Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}-mac
          name: Release v1.0.${{ github.run_number }}-mac
          files: |
            libft/libft.a
            includes/libft.h
            push_swap